packages:
  - name: pickle
    functions:
      - name: pickleblobber        
        runtime: python:default
        web: false
        limits:
          timeout: 15000
          memory: 512
        environment:  # Use the correct key for environment variables
          PICKLEJAR_ACCESS: ''
          PICKLEJAR_SECRET: ''
